name: medi_care
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

#----------------- PACKAGES ------------------#

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.9
  #logger: ^2.0.2 may not need


  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.4.6



  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific


  #--------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  #----------------- LOCAL ASSETS -------------------#

  assets:
    - assets/logos/
    - assets/fonts/
    - assets/images/

 #----------------- LOCAL FONTS ---------------------#
fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
        - style: italic
          asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
          weight: 400




